name: Docker Build and Export

on:
  push:
    branches: [main, master]
    tags: ["v*"]
  pull_request:
    branches: [main, master]

jobs:
  build-and-export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: screenshot-service:${{ steps.date.outputs.date }}-${{ github.sha }}
          load: true

      - name: Export Docker image to tar file
        run: |
          mkdir -p ./docker-images
          docker save screenshot-service:${{ steps.date.outputs.date }}-${{ github.sha }} > ./docker-images/screenshot-service-${{ steps.date.outputs.date }}-${{ github.sha }}.tar

      - name: Upload Docker image tar as artifact
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-service-image
          path: ./docker-images/screenshot-service-${{ steps.date.outputs.date }}-${{ github.sha }}.tar
          retention-days: 7
